// Generated by tools/guy-data.mjs from the `guy` sprite of assets-source/free-falling-girl.swf.
// The ragdoll rig exactly as authored: one entry per display-list child, with the properties
// its ClipActions set at load time. `p3` names a sibling, as `_parent.<name>` did in Flash.

export interface GuyChild {
  depth: number;
  char: number;
  name: string | null;
  x: number;
  y: number;
  xscale: number;
  yscale: number;
  rotation: number;
  is?: string;
  mass?: number;
  minang?: number;
  maxang?: number;
  inversed?: boolean;
  p3?: string;
}

export const GUY_CHILDREN: GuyChild[] = [
  { depth: 1, char: 2, name: "knee1", x: 35.4, y: 54.75, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.9 },
  { depth: 3, char: 2, name: "foot1", x: 21.4, y: 109.95, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.8 },
  { depth: 5, char: 2, name: "knee2", x: 85.4, y: 53.5, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.9 },
  { depth: 7, char: 2, name: "foot2", x: 108.45, y: 106.95, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.8 },
  { depth: 9, char: 2, name: "pants", x: 58.4, y: -2.05, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 1.1 },
  { depth: 11, char: 2, name: "stomach", x: 60.9, y: -42, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 1 },
  { depth: 13, char: 2, name: "head", x: 60.25, y: -129.9, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 1 },
  { depth: 15, char: 2, name: "arm2", x: 113.45, y: -94.5, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.5 },
  { depth: 17, char: 2, name: "hand2", x: 176.4, y: -96.5, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.5 },
  { depth: 19, char: 2, name: "arm1", x: 16, y: -94.5, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.5 },
  { depth: 21, char: 2, name: "hand1", x: -46.3, y: -93.75, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.5 },
  { depth: 23, char: 2, name: "neck", x: 59.4, y: -90.75, xscale: 47.46, yscale: 47.46, rotation: 0, is: "particle", mass: 0.5 },
  { depth: 25, char: 4, name: null, x: 57.15, y: -53.3, xscale: 51.54, yscale: 100, rotation: -90, is: "angledConstraint", minang: -0.5, maxang: 1, p3: "head" },
  { depth: 27, char: 4, name: null, x: 59.25, y: -134.3, xscale: 30.83, yscale: 100, rotation: 90, is: "angledConstraint", minang: -1, maxang: 0.5, p3: "stomach" },
  { depth: 29, char: 4, name: null, x: -49.05, y: -93.75, xscale: 51.54, yscale: 100, rotation: 0, is: "angledConstraint", minang: -0.1, maxang: 2.6, p3: "neck" },
  { depth: 31, char: 4, name: null, x: 56.25, y: -95.5, xscale: 51.54, yscale: 100, rotation: 180, is: "angledConstraint", minang: -2.6, maxang: 0.1, p3: "hand1" },
  { depth: 33, char: 4, name: null, x: 68.9, y: -102, xscale: 51.54, yscale: 100, rotation: 0, is: "angledConstraint", minang: -2.6, maxang: 0.1, p3: "hand2" },
  { depth: 35, char: 4, name: null, x: 177.9, y: -98.4, xscale: 51.54, yscale: 100, rotation: 180, is: "angledConstraint", minang: -0.1, maxang: 2.6, p3: "neck" },
  { depth: 37, char: 4, name: null, x: 63.1, y: -103.1, xscale: 51.54, yscale: 100, rotation: 90, is: "angledConstraint", minang: -0.4, maxang: 0.4, p3: "pants" },
  { depth: 39, char: 4, name: null, x: 64.3, y: -10.55, xscale: 51.54, yscale: 100, rotation: -90, is: "angledConstraint", minang: -0.4, maxang: 0.4, p3: "neck" },
  { depth: 41, char: 4, name: null, x: 54.7, y: 9.1, xscale: 51.54, yscale: 100, rotation: 105, is: "angledConstraint", minang: -0.1, maxang: 2.3, p3: "foot1" },
  { depth: 43, char: 4, name: null, x: 22.7, y: 113.25, xscale: 51.54, yscale: 100, rotation: -75, is: "angledConstraint", minang: -2.3, maxang: 0.1, p3: "pants" },
  { depth: 45, char: 4, name: null, x: 62.4, y: 11.25, xscale: 51.53, yscale: 99.97, rotation: 69.73, is: "angledConstraint", minang: -0.1, maxang: 2.3, p3: "foot2" },
  { depth: 47, char: 4, name: null, x: 107.55, y: 107.35, xscale: 51.53, yscale: 99.97, rotation: -110.27, is: "angledConstraint", minang: -2.3, maxang: 0.1, p3: "pants" },
  { depth: 49, char: 4, name: null, x: 92.2, y: 52.65, xscale: 51.53, yscale: 99.97, rotation: -110.27, is: "angledConstraint", minang: -0.3, maxang: 2.1, p3: "stomach" },
  { depth: 51, char: 4, name: null, x: 74.15, y: -61.85, xscale: 51.47, yscale: 99.86, rotation: 91.53, is: "angledConstraint", minang: -2.1, maxang: 0.3, p3: "knee2" },
  { depth: 53, char: 4, name: null, x: 29.85, y: 51.05, xscale: 51.45, yscale: 99.81, rotation: -70.89, is: "angledConstraint", minang: -0.3, maxang: 2.1, p3: "stomach" },
  { depth: 55, char: 4, name: null, x: 46, y: -64.4, xscale: 51.47, yscale: 99.86, rotation: 91.53, is: "angledConstraint", minang: -2.1, maxang: 0.3, p3: "knee1" },
  { depth: 57, char: 4, name: null, x: 126.85, y: -91.8, xscale: 51.54, yscale: 100, rotation: 180, is: "angledConstraint", minang: 0, maxang: 1.5707963267948966, inversed: true, p3: "stomach" },
  { depth: 59, char: 4, name: null, x: -2.25, y: -86.75, xscale: 51.54, yscale: 100, rotation: 0, is: "angledConstraint", minang: 0, maxang: 1.5707963267948966, inversed: true, p3: "stomach" },
  { depth: 61, char: 4, name: null, x: 71.75, y: -50.7, xscale: 51.54, yscale: 100, rotation: -90, is: "angledConstraint", minang: -1.5707963267948966, maxang: 0, inversed: true, p3: "arm2" },
  { depth: 63, char: 4, name: null, x: 49.8, y: -48.2, xscale: 51.54, yscale: 100, rotation: -90, is: "angledConstraint", minang: -1.5707963267948966, maxang: 0, inversed: true, p3: "arm1" },
];
