// GENERATED by tools/prepare-assets.mjs — do not edit by hand.
/** Baked body part textures: bone-aligned artwork, one pivot per part, all tiles the same square. */
export interface PartAsset {
  /** File name inside a character's own `parts` folder, i.e. `assets/characters/<folder>/parts`. */
  readonly file: string;
  /** Texture size, in pixels. Every part is baked into this same square. */
  readonly width: number;
  readonly height: number;
  /**
   * Where the bone turns, in pixels from the texture's top-left corner: the origin of the SWF's own
   * shape, which is the point the sprite is anchored to. All characters share it — the rig is the
   * movie's, and a character brings artwork to it, not a rig.
   */
  readonly pivotX: number;
  readonly pivotY: number;
  /**
   * World pixels one texel of the artwork covers. The sprite is drawn at full size and this density
   * lives in the asset itself (the scene gives the texture this resolution), rather than in a scale
   * the renderer would apply. 1 is the movie's own density — one texel per world pixel — and the
   * only bake that draws the artwork without resampling it.
   */
  readonly unitsPerTexel: number;
  /** Length of the artwork along the bone axis, in world pixels. */
  readonly partLen: number;
  /** Extent perpendicular to the bone axis, in world pixels. */
  readonly depth: number;
}

export const PART_ASSETS = {
  head: { file: 'head.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 63.000, depth: 49.000 },
  chest: { file: 'chest.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 75.200, depth: 51.500 },
  stomach: { file: 'stomach.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 63.900, depth: 52.200 },
  thigh: { file: 'thigh.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 93.000, depth: 43.000 },
  leg: { file: 'leg.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 90.200, depth: 46.750 },
  arm: { file: 'arm.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 76.500, depth: 33.600 },
  hand: { file: 'hand.png', width: 150, height: 150, pivotX: 75, pivotY: 75, unitsPerTexel: 1, partLen: 89.000, depth: 28.500 },
} as const satisfies Record<string, PartAsset>;

export type PartName = keyof typeof PART_ASSETS;
